package tests

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"testing"
	"time"

	"github.com/segmentio/kafka-go"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

type RunStartedEvent struct {
	RunID          string `json:"run_id"`
	SubmissionID   string `json:"submission_id"`
	ContestantID   string `json:"contestant_id"`
	SandboxAddress string `json:"sandbox_address"`
	TargetRPS      int    `json:"target_rps"`
	DurationSecs   int    `json:"duration_secs"`
	Protocol       string `json:"protocol"`
}

type TelemetryEvent struct {
	RunID       string `json:"run_id"`
	BotID       string `json:"bot_id"`
	OrderID     string `json:"order_id"`
	SentAtNs    int64  `json:"sent_at_ns"`
	AckAtNs     int64  `json:"ack_at_ns"`
	CorrectFill bool   `json:"correct_fill"`
	OrderType   string `json:"order_type"`
	Rejected    bool   `json:"rejected"`
}

func TestBotsPipelineIntegration(t *testing.T) {
	if testing.Short() {
		t.Skip("skipping integration test in short mode")
	}

	broker := os.Getenv("KAFKA_BROKERS")
	if broker == "" {
		broker = "localhost:9092"
	}
	brokers := []string{broker}
	
	ctx := context.Background()
	runID := fmt.Sprintf("pipeline-test-%d", time.Now().Unix())

	// Create a reader explicitly without a Consumer Group. 
	// This prevents a 10-15s group rebalance delay, allowing the test to read instantly.
	reader := kafka.NewReader(kafka.ReaderConfig{
		Brokers:   brokers,
		Topic:     "telemetry.raw",
		Partition: 0,
		MinBytes:  10e3,
		MaxBytes:  10e6,
	})
	defer reader.Close()
	
	// Seek to the end of the topic so we only consume events generated by this test
	_ = reader.SetOffset(kafka.LastOffset)

	writer := &kafka.Writer{
		Addr:     kafka.TCP(brokers...),
		Topic:    "run.started",
		Balancer: &kafka.LeastBytes{},
	}
	defer writer.Close()

	payload := RunStartedEvent{
		RunID:          runID,
		SubmissionID:   "sub-test",
		ContestantID:   "contestant-test",
		SandboxAddress: "dummy-orderbook:8080",
		TargetRPS:      20,
		DurationSecs:   2,
		Protocol:       "rest",
	}

	b, err := json.Marshal(payload)
	require.NoError(t, err)

	err = writer.WriteMessages(ctx, kafka.Message{
		Key:   []byte(runID),
		Value: b,
	})
	require.NoError(t, err, "failed to produce run.started event")

	// Allow up to 10 seconds for the bot fleet to scale up, process the 2-second run, 
	// and flush their telemetry batches to Kafka.
	readCtx, cancel := context.WithTimeout(ctx, 10*time.Second)
	defer cancel()

	matchedCount := 0

	for {
		msg, err := reader.ReadMessage(readCtx)
		if err != nil {
			break
		}

		var te TelemetryEvent
		if err := json.Unmarshal(msg.Value, &te); err != nil {
			continue
		}

		if te.RunID == runID {
			matchedCount++
			assert.NotEmpty(t, te.BotID)
			assert.NotEmpty(t, te.OrderID)
			assert.NotZero(t, te.SentAtNs)
		}
	}

	assert.Greater(t, matchedCount, 0, "expected telemetry events to be published")
}
